---
# Deployment file:-

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: lakshminathreddy/aws
        ports:
        - containerPort: 8080 
---
# service file
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30500
  selector:
    app: tomcat
  type: NodePort  
